version: '3'

services:
  museum-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: museum-system
    volumes:
      - .:/app
      # Mount PulseAudio socket for audio
      - ${XDG_RUNTIME_DIR:-/run/user/1000}/pulse:/run/user/1000/pulse
    ports:
      - "1883:1883"
    environment:
      - PYTHONUNBUFFERED=1
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - DISPLAY=${DISPLAY}
    # Add device mappings for audio and any hardware needed
    devices:
      - /dev/snd:/dev/snd
    # For X11 forwarding if needed
    network_mode: host
    # Add shared memory for audio processing
    shm_size: 2gb
    restart: unless-stopped 